import { AIProviderMeta, AIProviderType } from './types';

export const AI_PROVIDERS: Record<AIProviderType, AIProviderMeta> = {
  gemini: {
    id: 'gemini',
    name: 'Google Gemini',
    badge: 'Free Tier',
    description: 'Generous free tier with strong multimodal and structured output support.',
    defaultBaseUrl: 'https://generativelanguage.googleapis.com',
    requiresApiKey: true,
    defaultModel: 'gemini-2.0-flash',
    consoleUrl: 'https://aistudio.google.com/app/apikey',
    docsUrl: 'https://ai.google.dev/',
    modelPresets: [
      { id: 'gemini-2.0-flash', label: 'Gemini 2.0 Flash (Fastest, Recommended)' },
      { id: 'gemini-1.5-flash', label: 'Gemini 1.5 Flash (Legacy Reliable)' },
      { id: 'gemini-1.5-pro', label: 'Gemini 1.5 Pro (Deep Context)' },
    ],
  },
  groq: {
    id: 'groq',
    name: 'Groq',
    badge: 'Ultra Fast',
    description: 'Ultra-low latency LPU inference (300+ tok/s). Instant meal parsing.',
    defaultBaseUrl: 'https://api.groq.com/openai/v1',
    requiresApiKey: true,
    defaultModel: 'llama-3.3-70b-versatile',
    consoleUrl: 'https://console.groq.com/keys',
    docsUrl: 'https://console.groq.com/docs',
    modelPresets: [
      { id: 'llama-3.3-70b-versatile', label: 'Llama 3.3 70B (Recommended)' },
      { id: 'llama-3.1-8b-instant', label: 'Llama 3.1 8B (Instant Speed)' },
      { id: 'mixtral-8x7b-32768', label: 'Mixtral 8x7B' },
    ],
  },
  openai: {
    id: 'openai',
    name: 'OpenAI',
    badge: 'Industry Benchmark',
    description: 'Reliable structured outputs, trusted global uptime.',
    defaultBaseUrl: 'https://api.openai.com/v1',
    requiresApiKey: true,
    defaultModel: 'gpt-4o-mini',
    consoleUrl: 'https://platform.openai.com/api-keys',
    docsUrl: 'https://platform.openai.com/docs',
    modelPresets: [
      { id: 'gpt-4o-mini', label: 'GPT-4o Mini (Affordable, Recommended)' },
      { id: 'gpt-4o', label: 'GPT-4o (Frontier Quality)' },
    ],
  },
  deepseek: {
    id: 'deepseek',
    name: 'DeepSeek',
    badge: 'Low Cost',
    description: 'Extremely cost-effective ($0.14/1M tokens) with near-frontier capability.',
    defaultBaseUrl: 'https://api.deepseek.com/v1',
    requiresApiKey: true,
    defaultModel: 'deepseek-chat',
    consoleUrl: 'https://platform.deepseek.com/api_keys',
    docsUrl: 'https://api-docs.deepseek.com/',
    modelPresets: [
      { id: 'deepseek-chat', label: 'DeepSeek-V3 Chat (Recommended)' },
      { id: 'deepseek-reasoner', label: 'DeepSeek-R1 (Reasoning)' },
    ],
  },
  anthropic: {
    id: 'anthropic',
    name: 'Anthropic Claude',
    badge: 'High Accuracy',
    description: 'Exceptional instruction-following for parsing complex or messy meals.',
    defaultBaseUrl: 'https://api.anthropic.com/v1',
    requiresApiKey: true,
    defaultModel: 'claude-3-5-haiku-20241022',
    consoleUrl: 'https://console.anthropic.com/settings/keys',
    docsUrl: 'https://docs.anthropic.com/',
    modelPresets: [
      { id: 'claude-3-5-haiku-20241022', label: 'Claude 3.5 Haiku (Fast, Recommended)' },
      { id: 'claude-3-5-sonnet-20241022', label: 'Claude 3.5 Sonnet (Deep Nuance)' },
    ],
  },
  openrouter: {
    id: 'openrouter',
    name: 'OpenRouter',
    badge: 'Multi-Model',
    description: 'Single API key access to hundreds of open-source and proprietary models.',
    defaultBaseUrl: 'https://openrouter.ai/api/v1',
    requiresApiKey: true,
    defaultModel: 'meta-llama/llama-3.3-70b-instruct',
    consoleUrl: 'https://openrouter.ai/keys',
    docsUrl: 'https://openrouter.ai/docs',
    modelPresets: [
      { id: 'meta-llama/llama-3.3-70b-instruct', label: 'Meta Llama 3.3 70B' },
      { id: 'google/gemini-2.0-flash-001', label: 'Gemini 2.0 Flash' },
      { id: 'qwen/qwen-2.5-72b-instruct', label: 'Qwen 2.5 72B' },
      { id: 'mistralai/mistral-large-2411', label: 'Mistral Large' },
    ],
  },
  custom: {
    id: 'custom',
    name: 'Custom / Local (Ollama)',
    badge: 'Private & Local',
    description: 'Connect to self-hosted Ollama, LM Studio, vLLM, or any OpenAI-compatible API.',
    defaultBaseUrl: 'http://192.168.1.100:11434/v1',
    requiresApiKey: false,
    defaultModel: 'llama3.2',
    consoleUrl: 'https://ollama.com/',
    docsUrl: 'https://github.com/ollama/ollama',
    modelPresets: [
      { id: 'llama3.2', label: 'Llama 3.2 (Local)' },
      { id: 'mistral', label: 'Mistral (Local)' },
      { id: 'qwen2.5', label: 'Qwen 2.5 (Local)' },
    ],
  },
};

export const DEFAULT_AI_PROVIDER: AIProviderType = 'gemini';
